openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/hanssak/IW-API/1.0.0
info:
  description: This is a HS Cloud API
  version: "1.0.0"
  title: HS Cloud API
  contact:
    email: hsrnd1@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: 1. 신청
    description: '회원 가입 신청, 탈퇴, 관리자 승인, 알림등 사용자 이벤트 처리 Cycle'  
  - name: 2. 생성
    description: 'Cloud SaaS관련: 제품(솔루션), 인프라, 서버, 네트워크 생성 및 구성'
  - name: 3. 인증
    description: '로그인, 인증, 인가, 토큰 발급 (검증)'
  - name: 4. 관리
    description: '[SA연동] 시스템(Tenent, VM, IW-SA 서비스), Cloud(Network, VM, Storage) 제어 '
  - name: 5. 운영
    description: '[SA연동] 모니터링, 오토스케일링 상태 관리'
  - name: 6. 과금
    description: '[SA연동] SaaS 미터링, 빌링, 청구서 관리'
  - name: 7. 패치
    description: '[SA연동] 업데이트, 백업, 복구'


paths:
  '/member/users/{id}':
    post:
      tags: 
        - 1. 신청
      summary: '1.2.1 회원 가입 : 포털을 통한 회원가입 신청'
      description: '가입요청 신청: 서비스포털 -> API Gateway -> GateKeeper'
      operationId: createUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input, object invalid
        '409':
          description: An existing user already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Create user object
        required: true
    get:
      tags:
        - 1. 신청
      summary: '1.2.1 회원 가입 : 포털을 통한 회원가입 신청'
      operationId: 'ID확인요청: 서비스포털 -> API Gateway -> GateKeeper'
      parameters:
        - name: id
          in: path
          description: The name that needs to be fetched.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found

  '/invite':
    post:
      tags:
        - 1. 신청
      summary: '1.2.3 회원 가입 : 초대장을 통한 가입'
      description: '구성원 추가 : 관리포털 -> API Gateway -> Speaker'
      operationId: invitesUser
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: email
      responses:
        default:
          description: successful operation


components:
  schemas:
    Tenent:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: 테넌트 ID
        groupName:
          type: string
    User:
      type: object
      required: 
        - id
        - password
        - username
        - tenentId
        - isApprove
      properties:
        id:
          type: string
        password:
          type: string
          description: 암호화 필수
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        isApprove:
          type: boolean
          default: false
          description: '가입승인 처리 (false: 미승인, true: 승인)'
        tenent:
          $ref: '#/components/schemas/Tenent'
    Noti:
      type: object
      description: '현재 Payload만 구성됨 --> MQ, REST 쓸지 정해지지 않음'
      required: 
        - type
        - message
      properties:
        type: 
          type: string
          description: '알림 타입: kakao, email, phone'
          default: 'email'
        msg:
          type: string
          description: '메세지 내용'
    ResponseMsg:
      type: object
      description: 'REST API 응답 객체'
      properties:
        msg:
          type: string
          description: 'Response 세부 내용 기입'