openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/hanssak/IW-API/1.0.0
info:
  version: "1.0.0"
  title: HS Cloud API
  contact:
    email: hsrnd1@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'


tags:
  - name: 1. 신청
    description: '회원 가입 신청, 탈퇴, 관리자 승인, 알림등 사용자 이벤트 처리 Cycle'  
  - name: 2. 생성
    description: 'Cloud SaaS관련: 제품(솔루션), 인프라, 서버, 네트워크 생성 및 구성'
  - name: 3. 인증
    description: '로그인, 인증, 인가, 토큰 발급 (검증)'
  - name: '4.1 관리: 조직관리'
    description: '관리포털에서 사용하는 사용자 조직 관리 (Cloud관리자)'
  - name: '4.2 관리: 사용자 설정'
    description: '서비스포털에서 사용하는 유저 설정: 서비스 관리자 및 서비스포털 이용자) <br> (탈퇴, 정보 업데이트, 프로필 가져오기, 패스워드변경, 레포트, 구독정보)'
  - name: '4.3 관리: 시스템'
    description: '[SA연동] 시스템(Tenent, VM, IW-SA 서비스), Cloud(Network, VM, Storage) 제어 '
  - name: 5. 운영
    description: '[SA연동] 모니터링, 오토스케일링 상태 관리'
  - name: 6. 과금
    description: '[SA연동] SaaS 미터링, 빌링, 청구서 관리'
  - name: 7. 패치
    description: '[SA연동] 업데이트, 백업, 복구'

paths:
  '/gatekeeper/register':
    post:
      tags:
        - 1. 신청
      summary: '1.2.1, 1.2.2 회원 가입 : 사용자 생성 #RegisterId'
      description: '\- 가입요청 신청: 서비스포털 -> API Gateway -> GateKeeper <br> 제공된 ID는 고유해야 합니다. 또한 등록이 성공적으로 완료되면 제공된 주소로 확인 이메일을 보내야합니다.'
      operationId: RegisterId
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          description: 'ID 생성 성공'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
                  token:
                    type: string
                    example: '1mx6L2L7AMdEsyKy5LW9s8gt6mBxdICwosVn5sjhbwykOoQJFUru6752dwsj2THN'
        409:
          $ref: '#/components/responses/Conflict'
  '/gatekeeper/user-confirm':
    post:
      tags:
        - 1. 신청
      summary: '1.2.1, 1.2.2 회원 가입 : 중복 ID 확인 #UserConfirm'
      description: '\- 회원가입 시 ID 확인: 서비스포털 -> API Gateway -> GateKeeper <br> ID 중복 확인 요청'
      operationId: UserConfirm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - id
              properties:
                id:
                  type: string
      responses:
        200:
          description: '아이디 생성 가능 (중복 없음)'
        409:
          $ref: '#/components/responses/Conflict'
  '/speaker/invite':
    post:
      tags:
        - 1. 신청
      summary: '1.2.3 회원가입 : 사용자 초대 #invite'
      description: '\- 클라우드관리자가 사용자에게 초대장 전송: 관리포털 -> API Gateway -> Speaker <br> 이메일 형태로 전송해야 함'
      operationId: Invite
      security:
        - bearerAuth: []
      parameters: 
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            example: 'JWT Token'
          description: '관리자가 초대하는 URL로 인증된 사용자가 해야함'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Noti'
        description: '이메일 초대장으로 type:email을 설정해야합니다.'
      responses:
        default:
          description: successful operation

  '/apply/products/{name}':
    get:
      tags:
        - 2. 생성
      summary: '1.3.1 SaaS 신청: SaaS상품 라이센스 조회 #GetApplyProduct'
      description: ': 서비스포털 -> API Gateway -> Configurator <br> 상품 (SG, PG, OG)선택 후 제품 신청의 초기단계 '
      operationId: GetApplyProduct
      security:
        - bearerAuth: []
      parameters: 
        - name: name
          in: path
          required: true
          description: '상품명을 기입해야함 (예시: securegate, passguard)'
          schema:
            type: string
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            example: 'JWT Token'
      responses:
        '200':
          description: '상품에 따른 라이센스 종류 정보'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvisioningService'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      tags:
        - 2. 생성
      summary: '1.3.1 SaaS 신청: SaaS상품 구성정보 (웹으로 모든 구성필요)  #PostApplyProduct'
      description: ': 서비스포털 -> API Gateway -> MetaDataManager -> SaaS Builder <br> 각 Cloud와 연동하여 모든 솔루션 설정을 완료한 정보여야 합니다. 망연계일 경우 3개 장비 세트로 움직이게 됩니다.'
      operationId: PostApplyProduct
      security:
        - bearerAuth: []
      parameters: 
        - name: name
          in: path
          required: true
          description: '상품명을 기입해야함 (예시: securegate, passguard)'
          schema:
            type: string
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            example: 'JWT Token'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceMetaData'
        description: '구성한 상품정보 생성 요청으로 사전 cloud와 vpc정보 수용 필요'
      responses:
        '201':
          description: '정상적으로 생성 되었습니다.'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          description: '이미 생성되어있습니다. (충돌 발생)'
  #'/apply/products/{name}/status':
    
          
          
  '/member/users/{id}':
    get:
      tags:
        - '4.2 관리: 사용자 설정'
      summary: '1.2.1 회원 가입 : 포털을 통한 회원가입 신청 #GetUser'
      description: ': 서비스포털 -> API Gateway -> GateKeeper <br> ID확인요청'
      operationId: GetUser
      parameters:
        - name: id
          in: path
          description: The name that needs to be fetched.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags: 
        - '4.2 관리: 사용자 설정'
      summary: '1.2.1 회원 가입 : 포털을 통한 회원가입 신청 / 1.2.3 회원가입 : 클라우드 관리자가 ID 직접 발급  #PostUser'
      description: ': 서비스포털 -> API Gateway -> GateKeeper <br> 가입요청 신청'
      operationId: PostUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Successful create operation
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: Create user object
        required: true
    patch:
      tags:
        - '4.2 관리: 사용자 설정'
      summary: '1.2.2 회원가입 : 회원가입 신청 승인 #PatchUser'
      description: ': 관리포털 -> API Gateway -> GateKeeper <br> 가입요청에 대한 관리자 승인처리'
      operationId: PatchUser
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          $ref: '#/components/responses/NotFound'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                isApprove:
                  type: boolean
    delete:
      tags:
        - '4.2 관리: 사용자 설정'
      summary: '1.2.5 회원 탈퇴 #DeleteUser'
      description: ': 서비스/관리포털 -> API Gateway -> GateKeeper <br> 구성원 삭제 '
      operationId: DeleteUser
      parameters:
        - name: jwt
          in: header
          required: false
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'



components:
  # --> 보안 스키마 정의 
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT Authoriztion header using the Bearer scheme"
  
      
  # --> 응답 컴포넌트 정의
  responses:
    BadRequest:
      description: '400: 없는 필드 요청으로 에러 발생 (Field validation 실패)'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: '401: API인증 실패 (token is missing or invalid)'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: '404: 리소스 찾을수 없음'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: '409: 리소스 충돌 발생'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    
  # --> 데이터 스키마 정의
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required: 
        - code
        - message

    Tenent:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: 테넌트 ID
        groupName:
          type: string
          
    User:
      type: object
      required: 
        - id
        - password
        - username
        - isApprove
        - email
      properties:
        id:
          type: string
          example: 'id@hsck.com'
          description: 도메인 형식
        password:
          type: string
          description: 암호화 필수
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        isApprove:
          type: boolean
          default: false
          description: '가입승인 처리 (false: 미승인, true: 승인)'

    Noti:
      type: object
      description: '#oNoti 현재 Payload만 구성됨 --> MQ, REST 쓸지 정해지지 않음'
      required: 
        - type
        - from
        - to
        - msg
      properties:
        type: 
          type: string
          description: '알림 타입: kakao, email, phone'
          default: 'email'
        from:
          type: string
          description: '발신자 주소'
          default: 'hsck@hsck.com'
        to:
          type: string
          description: '수신자 주소'
          default: 'user@company.com'
        msg:
          type: string
          description: '메세지 내용'
    
    ProvisioningServiceInfo:
      type: object
      properties:
        level:
          type: string
          default: 'basic'
          description: 'SaaS의 상품 등급 (Lite, Basic, Premium)'
        content:
          type: string
          example: 'basic 라이센스에 관한 내용'
          description: '설명'
        spec:
          type: string
          description: '사양'
        pricing:
          type: string
          description: '요금'
    ProvisioningService:
      type: object
      description: '사전에 정의된 SaaS상품의 정보 스키마'
      properties:
        product:
          type: string
          example: 'securegate'
          description: 'SaaS 상품 ID : securegate, passwordguard, officegate'
        info:
          type: array
          items:
            $ref: '#/components/schemas/ProvisioningServiceInfo'
            
    NcpServerConfigTf:
      type: object
      description: '네이버 클라우드 전용: 솔루션 서버 설정 정보 (server_code는 HS전용코드)'
      required: 
        - server_code
      properties:
        server_code:
          type: string
          format: XX.XX.XX.1234
          description: '제품+서버+사양+시퀀스의 합산코드로 제품서버생성에 사용되는 코드입니다. <br> 예시) SG.IN.PM.101'
        vpc_no:
          type: integer
          format: int32
          description: ''
        subnet:
          type: string
          format: ipv4/prefix
          description: 'x.x.x.x/24'
        subnet_no:
          type: integer
          format: int32
          description: '서버를 생성한 서브넷 번호를 지정합니다. <br> 신규 서브넷 생성 시 공란으로 해야합니다.'
        public_ip:
          type: boolean
          description: '공인IP 사용 여부 <br> (단, 서브넷에서 공인망을 사용하지 않는 경우 사용불가합니다.'
          
    ServiceMetaData:
      type: object
      description: '솔루션의 상품 구성한 모든 정보를 담고 있는 스키마'
      required:
        - product
        - tenent
        - server_config
      properties:
        product:
          type: string
        server_config:
          type: array
          items:
            $ref: '#/components/schemas/NcpServerConfigTf'

      
    
    
      
    ResponseMsg:
      type: object
      description: 'REST API 응답 객체'
      properties:
        msg:
          type: string
          description: 'Response 세부 내용 기입'